/**
 * Einbettet content/*.md zur Build-Zeit in TypeScript.
 * So funktioniert die API zuverlässig auf Vercel (kein fs zur Laufzeit).
 */
const fs = require("fs");
const path = require("path");

const contentDir = path.join(__dirname, "..", "content");
const outFile = path.join(__dirname, "..", "lib", "embedded-content.generated.ts");

const files = ["system-prompt.md", "knowledge-base.md"];

const items = [];
for (const file of files) {
  const filePath = path.join(contentDir, file);
  if (!fs.existsSync(filePath)) {
    throw new Error(`Content file not found: ${filePath}`);
  }
  const content = fs.readFileSync(filePath, "utf-8").trim();
  const varName = file
    .replace(".md", "")
    .split("-")
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join("");
  items.push({ name: varName, content });
}

const tsContent = `// Auto-generated by scripts/embed-content.cjs – do not edit manually
${items
  .map(
    (e) =>
      `export const ${e.name} = ${JSON.stringify(e.content)} as const;`
  )
  .join("\n\n")}
`;

fs.mkdirSync(path.dirname(outFile), { recursive: true });
fs.writeFileSync(outFile, tsContent, "utf-8");
console.log("Embedded content:", files.join(", "));
